### ISSUE TITLE
issue with Jikan API

### ISSUE THREAD

**Issue by Ammourie** [jikan-me/jikan-rest#160]
Thank you for the wonderful API
Recently i am testing the Characters Section of Anime
It give me only one  character from the Anime [All Animes ]
I have no idea why this happen 
https://api.jikan.moe/v3/anime/16353/characters_staff
It was working perfectly before now 
Can you fix it soon?
Thank you very mush

**Comment by irfan-dahir** [comment]
Hey, this issue was already resolved:
https://github.com/jikan-me/jikan/issues/362

What you're seeing is cache. I've gone ahead and invalidated that so the appropriate response should now be visible.

I'm closing this issue as it's duplicate. Feel free to ping me on the linked issue if any other cache appears bugged!
