### ISSUE TITLE
[OFFICIAL] Generated Issue: InvalidArgumentException

### ISSUE THREAD

**Issue by koji98** [jikan-me/jikan-rest#174]
Please fill out the details below.

**Summary:**
Using the API to get the anime occurring in a season results in a http 500 code a lot.

**Steps to reproduce:**
Request `https://api.jikan.moe/v3/season/2020/spring`

 ### Additional Details 
 **Jikan Parser Version**: ```v2.18.13@d41c4535bb739824c61ae22192c41eb3b705399c```
**PHP:** ```7.4.23```
**Redis**: ```Connected```
**Exception:** ```InvalidArgumentException```
**Code:** ```0```
**Message:** ```Status code must be an integer value between 1xx and 5xx.```
**Trace:** ```/var/www/jikan/vendor/guzzlehttp/psr7/src/Response.php on line 152```
**Request:** `GET /v3/season/2020/spring`

**Comment by irfan-dahir** [comment]
Okay so there's 2 issues here at play at this very moment.

1. There's currently a parser issue due to HTML change that's affecting endpoints like season, genres, schedule, etc.
You can track that here: https://github.com/jikan-me/jikan/issues/386

2. However, if you are getting specifically HTTP 5xx errors that's returning a message like `Status code must be an integer value between 1xx and 5xx.` and this has affected you from any other responses.
Please read: https://github.com/jikan-me/jikan-rest/issues/177

**Comment by irfan-dahir** [comment]
Just to update you that the # 1 mentioned parser issue has been resolved. You can read more about it here: https://github.com/jikan-me/jikan/issues/386

For the # 2 issue, please track it by the pinned issue I created #177 . I'll be closing this issue.
