### ISSUE TITLE
Update Anime/Manga SFW Policy

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#218]
Needs to be reworked.

Anime filters out Rx types and Manga filters out Doujinshi type.
This is not appropriate as other entry types can contain hentai/nsfw stuff.

Most likely will have to filter out by genre instead.
Also need to explore filter Implementation on API endpoints as well as whether it's duo or tri state.

Duo state
`?sfw` only check for filter presence. Filters out nsfw entries

Tri state
`/?` no filter set. Results return everything by default
`?sfw=true` returns only sfw entries
`?sfw=false` returns only hentai/nsfw entries

Todo
- check filter implementation with mongodb query on duo/tri state
- explore API endpoints this can be implemented on
- setup SFW Policy (genres that will be excluded for maximizing SFW results)

**Comment by irfan-dahir** [comment]
### Finalized policy

User can pass `sfw` in-query without any value on the following resource types with the following exclusions
| Resource Types | Resource Exclusions |
| ---------- | ---------- |
| Anime | **Genres:** [Erotica](https://myanimelist.net/anime/genre/49/Erotica), [Hentai](https://myanimelist.net/anime/genre/12/Hentai)<br />**Rating:** `Rx - Hentai` |
| Manga | **Genres:** [Erotica](https://myanimelist.net/manga/genre/49/Erotica), [Hentai](https://myanimelist.net/manga/genre/12/Hentai) |

Implementation will be done on #346

**Comment by irfan-dahir** [comment]
Resolved with https://github.com/jikan-me/jikan-rest/pull/346

**Comment by Prid13** [comment]
Does this include NSFW cover arts? Cause I'm seeing a few false positives 😅

Search for "Highschool of the Dead: Drifters of the Dead" and "Utsukushiki Sei no Reirei"

**Comment by irfan-dahir** [comment]
@Prid13 Please share the request and response details

**Comment by irfan-dahir** [comment]
@Prid13 Fixed with #390 

https://api.jikan.moe/v4/anime?sfw&q=Utsukushiki%20Sei%20no%20Reirei


As for "Highschool of the Dead: Drifters of the Dead", this is an ecchi anime. And we're not targetting those in SFW for now. You can use `genres_exclude=9` to remove any ecchi titles.

**Comment by happykuntal** [comment]
uys, I have an anime website, and I’m looking for an API that can help users easily watch and download anime on my site. Can someone provide this?

**Comment by Prid13** [comment]
Hey @happykuntal :)

APIs like this one provide public open data like anime details, dates, episode list, images, etc. I think this is mostly within legal bounds, so there's no fear of it getting taken down :) Also, hosting large amount of TEXT isn't an issue with today's storage capacities and prices.

However, streaming anime and offering links to streaming anime episodes is completely different and will be aggressively targeted by official companies and they will be taken down, especially if they get popular and amass tons of viewers.

There are two issues:

  1.
Hosting anime: you can't use youtube or other free video hosting services to host anime — they will get detected and taken down. And you can't host it yourself either, mostly bc of how costly it would be to store hundreds of GBs of anime, and the bandwidth costs when all your thousands of users stream the content.
That's why you have to find some free (or cheap) hosting services that aren't well known, and upload/host the episodes there (like Google Drive, Mega, Pomf clones, etc.).
However, they will also get taken down once discovered, so you have to keep re-uploading (which means you will get new streaming urls every time).
  2.
Offering links to anime episodes: this is much easier bc it costs nothing, but this will also be targeted by official companies and will probably get taken down. If you don't host episodes yourself, you will have to find direct links to anime episodes other websites have hosted, but Jikan can't provide this without risking the whole API being targeted and being forcibly shut down... :(
Another issue is that even if direct links were available in the API, they would probably need to be updated all the time for every single episode bc after they get taken down, they would need to be re-uploaded by those who host the episodes, and thus a new url for the episode would be generated, and this can be a tedious job to maintain.

Nonetheless, I did try to search around for what you're asking for, and it seems like almost all publicly hosted APIs that offer streaming links to anime episodes don't work anymore... :/ (they probably got taken down, or aren't being maintained anymore).

Publicly Hosted APIs:

  *
https://github.com/Shalin-Shah-2002/Hianime_API (most recent and most promising, however i didn't get any working urls from the api endpoints)
     *
e.g. https://hianime-api-b6ix.onrender.com/api/stream/15670?server_type=sub (not returning any links)
  *
https://www.sankavollerei.com/anime/ (the only working, comprehensive api with real streaming links, BUT, it's indonesian, and episodes seem to have hardcoded indonesian subs 😅)
     *
e.g. https://www.sankavollerei.com/anime/stream/episode/one-piece-episode-008
  *
https://github.com/Anispace/api<https://github.com/Anispace/api?tab=readme-ov-file> (doesn't work anymore it says)

There may be some obscure hosted API somewhere, but if I were to find it easily, then it probably wouldn't have been safe for long 😅

What I did find, however, are a dozen of github repos that offer self-hosted solutions for scraping content from "free anime watching websites" (like 9anime, hianime, etc.). This will require you to get your own server, or use some kind of free server (like cloudflare worker), which is used to scrape the websites' content and fetch direct links to anime episodes, and you'd need to host the REST API (JSON) as well to get those links.

Self-hosted Scraping Options:

  *
https://github.com/ghoshRitesh12/aniwatch-api (there's instructions on how to host it on Vercel or Render)
  *
https://github.com/yahyaMomin/hianime-API (button to deploy to Render)
  *
https://github.com/ryanwtf88/toonstream-api (instructions for deployment to CloudFlare Workers)
  *
https://github.com/ryanwtf88/hianime-api?tab=readme-ov-file#installation (instructions for CloudFlare Workers, Vercel and Replit)
  *
https://github.com/mnuddindev/jutsu-api
  *
https://github.com/shimizudev/anicrush-api

These can be hosted somewhere for free (like CloudFlare Workers, Vercel, Render, etc.), or hosted on your self-purchased server somewhere, or simply run locally on your computer (but then only you would have access to the links, unless you decide to open your local network to the public internet — but don't do that unless you know what you're doing 😅)

If you're feeling adventurous, you could try fetching magnet links to torrents at Nyaa, and letting users stream those directly via WebTorrent ;) (see webtor.io. copy any magnet link from nyaa or other website, paste it there, and click on "Stream", and wait slightly, and then watch the magic happen)

But as you can see, video hosting and keeping videos up are two of the greatest challenges when it comes to this (storage and bandwidth costs for the first one, and legal issues with the second one), which is exactly why you won't find any of this easily available anywhere. And even if you do, it probably won't stay up for long. So your best bets are running those scraping scripts somewhere and getting streaming links that way 🙂

Wish you the best on your adventure and site and personal life ⭐😇

(Hopefully the links provided above stay up for the foreseeable future. If not, I'm really sorry I brought attention to you 🙁 Accept my apologies in advance)
________________________________
Fra: Abhay Kuntal ***@***.***>
Sendt: mandag 19. januar 2026 13:03
Til: jikan-me/jikan-rest ***@***.***>
Kopi: Prid13 ***@***.***>; Mention ***@***.***>
Emne: Re: [jikan-me/jikan-rest] Update Anime/Manga SFW Policy (Issue #218)

[https://avatars.githubusercontent.com/u/139948243?s=20&v=4]happykuntal left a comment (jikan-me/jikan-rest#218)<https://github.com/jikan-me/jikan-rest/issues/218#issuecomment-3767993136>

uys, I have an anime website, and I’m looking for an API that can help users easily watch and download anime on my site. Can someone provide this?
