### ISSUE TITLE
Search min max score filters do not work as expected

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#309]
Issue mentioned here: https://discord.com/channels/460491088004907029/1047092059670065162/1047092059670065162

> Also the results seem to be cut in half if I add &min_score=0.0&max_score=10.0 (from 955 to 595) even if it shouldn't really do anything and show everything between 0 and 10.

This is for `v4.0.0-rc.6`.

**Comment by pushrbx** [comment]
Just to clarify this one:
When the request is:
```
https://api.jikan.moe/v4/anime?genres=1,2&min_score=0.0&max_score=10.0
```
It doesn't work as expected, because filtering by genres has an issue.

Regarding the other bit "results seem to be cut in half if I add min_score=0.0&max_score=10.0":
If you specify this range you also filter out those entries which doesn't have score at all.
