### ISSUE TITLE
Spaces in example: "https://api.jikan.moe/v3/anime/5114/", related objects

### ISSUE THREAD

**Issue by freja96** [jikan-me/jikan-rest#37]
Spaces and dash(-)
`    "related": {
        "Adaptation": [
            {
...
            }
        ],
       "Alternative version": [
            {
...
            }
        ],
        "Side story": [
            {
            ...
            },
            {
...
            }
        ],
        "Spin-off": [
            {
...
            }
        ]`

**Comment by irfan-dahir** [comment]
This is because the PHP parser automatically parses those "types" as key string in an associative array. Thus the Serializer on the REST API ends up putting them that way in the response too.

It would be a major change to the API if I were to correct it now, so it's a proposed for the next major release.

There's an issue on this open, I will close this one. #32
