### ISSUE TITLE
typesense 0.24.1 Search inaccuracies

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#386]
It's causing search inaccuracies. 

There seems to be a result disparity between 0.23.1 and 0.24.1.
0.24.1 has some search inaccuracies where 
- it's ranking an irrelevant result higher than the intended result
- it's not picking up 'fate zero', but it picks up 'fate/zero'
- 'death parade' doesn't return
- 'oshi no ko' doesn't return. the entry has some glyphs in the title so 0.24.1 expects the exact phrase (this is not the case in 0.23.1)
- 'naruto shippuden' returns 'naruto' as the first result - again not the case in 0.23.1

**Comment by pushrbx** [comment]
There was a major change in `0.24.1`: They added "bucketing" feature to text match scores. I tried to play around with it, and it seems that we need to set the bucket size to the number of items we are trying to return on a single page. Currently this number is 25 by default.

**Comment by pushrbx** [comment]
I'm making a note of other discovery here:
- If you look for `aldnoahzero` you only get aldnoah zero, but the built-in tokenizer of typesense won't break the term `aldnoahzero` down to two words, so there won't be any hits for `aldnoah` and `zero` individually.
- This behavior can be observed on MAL: if you search for `aldnoahzero` you can see that internally their software breaks it down to smaller words.

Overall it's not a big deal, because the user will just try different search terms if the number of hits are low. E.g. starts with `fatezero`, then fixes it to `fate zero`.

**Comment by pushrbx** [comment]
### Findings with v0.24.1 of typesense

Default `sort_by` parameter value: `_text_match(buckets:25):desc,popularity:asc,rank:asc`
Collection tested: `anime_index`
`infix` parameter is set to `fallback`

- If the `drop_token_threshold` and the `typo_tolerance_threshold` is set to the number of items we want to return on a page, and `exhaustive_search` is turned off, I get good enough results.
- `fate/zero`, `fate zero` works
- `death parade` works
- `naruto shippuden` works as expected

**Comment by pushrbx** [comment]
#409 covers this

**Comment by irfan-dahir** [comment]
Resolved
