### ISSUE TITLE
Top with filter set to upcoming returns empty

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#388]
/top/anime?filter=upcoming&sfw=1

![image](https://github.com/jikan-me/jikan-rest/assets/9166451/37c20e51-53bc-437d-87e3-b7d6aeb3648a)

**Comment by pushrbx** [comment]
@irfan-dahir The problem is that we have a filter in place:
`rank must be greater than 0 and rank must not be null`
This returns zero results as most of upcoming items have no rank, or it's set to 0. Also for upcoming we wanted to have some sort of order maybe, and hence we went with this solution what we currently have. Probably we'd like to change it order by some other attribute instead.
