### ISSUE TITLE
Opening and Ending themes have second quote mark at start of string

### ISSUE THREAD

**Issue by Mr2u** [jikan-me/jikan-rest#43]
When getting info for an anime, the Opening and Ending theme arrays have a second " at the start of each string.

Example: https://api.jikan.moe/v3/anime/38759/ ( Meddlesome Kitsune Senko-san )
```
  "opening_themes": [
    ""Koyoi mofumofu!! (今宵mofumofu!!)" by Senko (Azumi Waki), Shiro (Maaya Uchida)"
  ],
  "ending_themes": [
    ""Moffumoffu DE Yoi no Ja yo (もっふもっふ DE よいのじゃよ)" by Senko (Azumi Waki)"
  ]```
```
This happens for all anime I've tested.
A simple workaround is to just remove that first character from each string, but thats slightly annoying.

Tested with nodejs request library and the official documentation console page thing

Edit: forgot to end code block lol

**Comment by irfan-dahir** [comment]
Hi, these quotations are present on MyAnimeList. It's not a second one actually, the quotes end before the word `by`.

`"XYZ" by abc`
**"**Koyoi mofumofu!! (今宵mofumofu!!)**"** by Senko (Azumi Waki), Shiro (Maaya Uchida)

It looks like two quotes because of the JSON format. Once you use it, it'll be viewed like this:
`"Koyoi mofumofu!! (今宵mofumofu!!)" by Senko (Azumi Waki), Shiro (Maaya Uchida)`

**Comment by Mr2u** [comment]
WOW I'm blind! Thanks for pointing this out.


I actually feel super stupid right now .w.
Sorry :p

**Comment by irfan-dahir** [comment]
No worries, easy to mistake it
