### ISSUE TITLE
🐛 Empty query string parameters cause an internal server error

### ISSUE THREAD

**Issue by nadla20xx** [jikan-me/jikan-rest#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API has returned an error: 
```TypeError```
Status code: ```0```
Message: ```Cannot assign string to property App\Dto\SearchCommand::$page of type Spatie\LaravelData\Optional|int```
Trace: ```/var/www/jikan-rest/vendor/spatie/laravel-data/src/Resolvers/DataFromArrayResolver.php on line 49```

### Expected Behavior

The API should have returned a successful response with data.

### Steps To Reproduce

Http Request: `GET /v4/anime?sfw=&unapproved=&page=&q=&sfw=&genres=&genres_exclude=&letter=&producers=&start_date=2001-01-01&end_date=2010-01-01

**Comment by pushrbx** [comment]
Probably we need to upgrade LaravelData package. The following PR might be a solution: https://github.com/spatie/laravel-data/pull/602
Otherwise some global transformer would be required, because all the endpoints are affected by this.
I mean if you set an empty param, you get an error message instead of treating it empty/non-existent.

@nadla20xx For now I can only recommend not passing empty params to the API.

**Comment by pushrbx** [comment]
Found the source of the issue, it wasn't the laravel data package version. :tada:
