### ISSUE TITLE
Add Archived Fansubs Info for Anime

### ISSUE THREAD

**Issue by irfan-dahir** [jikan-me/jikan-rest#65]
- Only available on select anime that had the data before MAL removed it

1. Connect with fansub archive repository to cache it server side
2. Inject it into JSON response (via Serializer probably?)

**Targeted Endpoints:**
`/anime/[Id]`

**Comment by irfan-dahir** [comment]
Some notes on how this might work.

| Endpoint |  Remarks |
| ------------- | ------------- |
| `/fansubbers` | List all fansub groups. Returns array of `name`, `mal_id`, `...` |
| `/search/fansubbers?q=` | Search fansub groups. Returns array of `name`, `mal_id`, `...` |
| `/fansubbers/{mal_id}` | Returns fansub group information & array of anime they've subbed |

Is there a better alternative terminology to `fansubbers`?

### `/fansubbers/{mal_id}`
| Property  |  Type | Remarks |
| ------------- | ------------- | ------------- |
| `mal_id` | Int | - |
| `name` | String | Group name |
| `short_name` | String | Group short name |
| `irc_url` | String | - |
| `primary_language` | String | - |
| `user_approval_votes` | Int | User approval count |
| `user_disapproval_votes` | Int | User disapproval count |
| `anime` | Array of **ANIME PROJECT OBJECT** | - |

#### ANIME PROJECT OBJECT
| Property  |  Type | Remarks |
| ------------- | ------------- | ------------- |
| `mal_id` | Int | Anime ID |
| `url` | Int | Anime URL |
| `title` | String | Anime Title |
| `type` | String | Anime Type (TV, OVA, Special, etc) |
| `episodes` | Int | Anime episode count |
| `user_approval_votes` | Int | - |
| `user_disapproval_votes` | Int | - |
| `comments` | Array of String | Anonymous Comments by voters |

**Comment by IA21** [comment]
`comments` also have the positive/negative (or approve/disapprove) property in addition to the content. MAL indicated this by using a light grey color as background for positive comments and light red for negative. So `comments` might be an array of objects with `content` and... `vote` (?) properties.

**Comment by IA21** [comment]
> Is there a better alternative terminology to fansubbers?

Don't think so. Even [wikipedia](https://en.wikipedia.org/wiki/Fansub#Process) uses the term fansubber:

> The practice of making fansubs is called fansubbing and is done by a fansubber

**Comment by irfan-dahir** [comment]
> comments also have the positive/negative (or approve/disapprove) property in addition to the content. MAL indicated this by using a light grey color as background for positive comments and light red for negative. So comments might be an array of objects with content and... vote (?) properties.

Had no idea. We can add this too. Though if it's just grey/red, the property might be preferable as a Boolean unless there's a neutral state too? 

> Don't think so. Even wikipedia uses the term fansubber
`Fansubber` is is then!

**Comment by IA21** [comment]
Nope, no neutral, just 2 states: grey and red.

**Comment by Prid13** [comment]
> Is there a better alternative terminology to fansubbers?

"Fansubbers" sounds really off. I've always ever heard the term "fansub group" be used by the people who partake in the fansubbing process. Because it's almost always a _group_ of people with different roles that work together to put out quality subs, and they usually have a name or an abbreviation they go by (enclosed by square brackets, e.g. [Unlimited Translation Works](https://utw.me) -> [UTW] and [Good Job! Media](https://www.goodjobmedia.com) -> [GJM], or just the group name, like [Kaleido-subs](https://github.com/Kaleido-subs) -> [Kaleido-subs] (who btw put out their fansubs [on github](https://github.com/Kaleido-subs/Kimetsu-no-Yaiba/blob/master/01/YaibaBD_01%20-%20Dialogue.ass)!) )

Maybe `fansub_groups` / `fansubgroups` could work better, even though it's a tad bit longer?

--------

As for information on which fansub groups are doing newer releases (i.e. not restricted by the MAL archive), [FansubDB.com](https://fansubdb.com/wiki/Winter_2021) is a great resource for that :)

**Comment by IA21** [comment]
Thanks for the tip about fansubdb.com. I have been using anidb since MAL removed fansub info.

**Comment by irfan-dahir** [comment]
Good to know a DB for fansub information exists. This has been a low-priority feature for a while now. I'm not sure whether I will be implementing this anytime soon (or if at all) since I do not see the demand for it.

One of the issues with adding this would be that it would be incomplete. New entries on MAL do not provide fansub information anymore so going forward we'd have to source that data from elsewhere and that would require some additional service scrapping and managing the existing data.

**Comment by IA21** [comment]
This would only work as a separate/miscellaneous feature instead of a full fledged fansubs endpoint on the main api. You're right about this being low priority and having very little demand. Most new anime watchers these days no longer look for fansubs and just watch whatever crunchy/netflix feed them. This feature would only be for stubborn, old school, die hard types that are still around, like me 🙂. Which is why my [MAL fansubs archive script](https://redd.it/9kq1ch) is still live.
